### ISSUE TITLE
Improve iOS OCR App to collect multiple images

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/Pt_Mobile_Application#11]

**Comment by arlin** [comment]
Is this issue about adding the functionality to build a tree from names collected from multiple images?  Please provide more description.

**Comment by arlin** [comment]
I think _incremental_ construction of the tree will be most interesting to users.  That is, rather than expecting the user to gather a set of names A, B, C ... Z and then retrieve the final tree, get the tree for the first 3 species, e.g. (A, (B, C)), then just keep "adding" to that by retrieving a new tree each time a species is added, e.g., ((A,D), (B,C)) and so on.

**Comment by thanhnh-infinity** [comment]
Yes, Arlin. I've got it. Keep working on it
