### ISSUE TITLE
Test OCR quality - Easy images folder - Longwood Gardens

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/Pt_Mobile_Application#19]

**Comment by thanhnh-infinity** [comment]
I tested  photos in Easy folder and notes result in easy.csv file.

**Comment by arlin** [comment]
Thanks, @thanhnh-infinity.  I looked at this and fixed two errors in the test list of species names.   

Is the percentage accuracy on a per-character basis?  We need to look at this also in the context of name-recognition.  Ailanthus becomes "anthus" and Alliara becomes "AMiaria".  In both cases, there was a somewhat blurry double image of "ll".   I wonder if we could still recognize these names via GNRD?  

I would no longer classify the bird list image as "easy" because of that.

**Comment by arlin** [comment]
I have checked with GNRD and those two cases are failures in the sense of getting the correct species.   If I send GNRD exactly the text that is scraped by OCR for the 12 species, it finds 10 species correctly and adds "Nakai anthus"  which is wrong.

**Comment by thanhnh-infinity** [comment]
@arlin : percentage accuracy right now, I try to quickly diagnose from equation correct characters/ total characters. I am not sure it is correct 100% because I count it manually. I will be correct them later. 

Yes, Dr Arlin, OCR cannot get 100% correct text in 100% cases. The most powerful tool also guarantees 90 - 98% depend on reality cases. So that the very important thing is GNRD can check and correct the species name. When I test iOS app, GNRD has no longer worked well to fix the in-correct name from species names. Such as in your example, when we send in-correct name like "AMiaria", we have not got correct "Alliara".

**Comment by arlin** [comment]
I have used your OCR results as input to GNRD to estimate the accuracy of going from image to validated name.  The results are pretty good.  I added the results to easy.csv and medium.csv.
