### ISSUE TITLE
Test OCR quality with 'hard' images

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#23]
'

**Comment by hdliv** [comment]
I have started to work on this, but don't know if it is a prioroty

**Comment by arlin** [comment]
@hdliv, please be sure to push any changes you made to hard.csv .

**Comment by hdliv** [comment]
I will. I haven't finished due to more 50 names on some

**Comment by arlin** [comment]
OK, I remember the problem.  It isn’t a rush.

On Mar 14, 2016, at 2:30 PM, Dail Laughinghouse <notifications@github.com<mailto:notifications@github.com>> wrote:

I will. I haven't finished due to more 50 names on some

—
Reply to this email directly or view it on GitHubhttps://github.com/phylotastic/Phylotastic_Mobile_Application/issues/23#issuecomment-196458922.

---

Arlin Stoltzfus (arlin@umd.edumailto:arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.orghttp://www.molevol.org

**Comment by hdliv** [comment]
@arlin hard.csv has been updated
