### ISSUE TITLE
Improve Home view appearance

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#58]
Improve Home view appearance with logo and more consistent iOS styling, as described in design/mobile_app_mvp_priorities.pptx

**Comment by thanhnh-infinity** [comment]
Changed icons, disabled un-necessary icons; change color for header/footer menu; inserted Phylotastic icon in header menu

I removed Text and keep only icons for Home, Capture and Help because I thought that theses icons are enough meaning to let user understand what are their  actions. 

In addition, when I tried to use "icon is above text" for small screen (iPhone 4s; some android devices); It consumed space of main list. I feel a little bit ugly.

In new iOS version, (from version 8.0), Apple made some changes so that style for "icon is above text" is not perfect in header/footer menu

If you really want to display Text under Icon, please let me know. I will find the other way to implement that

**Comment by arlin** [comment]
I think this is a big improvement.
